package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsDyPrice;
import org.linlinjava.litemall.db.domain.LitemallGoodsDyPriceExample;

public interface LitemallGoodsDyPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsDyPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsDyPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsDyPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsDyPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    LitemallGoodsDyPrice selectOneByExample(LitemallGoodsDyPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    LitemallGoodsDyPrice selectOneByExampleSelective(@Param("example") LitemallGoodsDyPriceExample example, @Param("selective") LitemallGoodsDyPrice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    List<LitemallGoodsDyPrice> selectByExampleSelective(@Param("example") LitemallGoodsDyPriceExample example, @Param("selective") LitemallGoodsDyPrice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    List<LitemallGoodsDyPrice> selectByExample(LitemallGoodsDyPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    LitemallGoodsDyPrice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsDyPrice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    LitemallGoodsDyPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsDyPrice record, @Param("example") LitemallGoodsDyPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsDyPrice record, @Param("example") LitemallGoodsDyPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsDyPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dy_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsDyPrice record);
}