package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.room_address
     *
     * @mbg.generated
     */
    private String roomAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.duration
     *
     * @mbg.generated
     */
    private BigDecimal duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.video_name
     *
     * @mbg.generated
     */
    private String videoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.room_id
     *
     * @mbg.generated
     */
    private String roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.integral
     *
     * @mbg.generated
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.time
     *
     * @mbg.generated
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.number_static
     *
     * @mbg.generated
     */
    private Integer numberStatic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.begin_timeFrom
     *
     * @mbg.generated
     */
    private String beginTimefrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.begin_timeTo
     *
     * @mbg.generated
     */
    private String beginTimeto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_task.real_dieTime
     *
     * @mbg.generated
     */
    private String realDietime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.id
     *
     * @return the value of litemall_task.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.id
     *
     * @param id the value for litemall_task.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.room_address
     *
     * @return the value of litemall_task.room_address
     *
     * @mbg.generated
     */
    public String getRoomAddress() {
        return roomAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.room_address
     *
     * @param roomAddress the value for litemall_task.room_address
     *
     * @mbg.generated
     */
    public void setRoomAddress(String roomAddress) {
        this.roomAddress = roomAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.duration
     *
     * @return the value of litemall_task.duration
     *
     * @mbg.generated
     */
    public BigDecimal getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.duration
     *
     * @param duration the value for litemall_task.duration
     *
     * @mbg.generated
     */
    public void setDuration(BigDecimal duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.video_name
     *
     * @return the value of litemall_task.video_name
     *
     * @mbg.generated
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.video_name
     *
     * @param videoName the value for litemall_task.video_name
     *
     * @mbg.generated
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.number
     *
     * @return the value of litemall_task.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.number
     *
     * @param number the value for litemall_task.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.room_id
     *
     * @return the value of litemall_task.room_id
     *
     * @mbg.generated
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.room_id
     *
     * @param roomId the value for litemall_task.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.state
     *
     * @return the value of litemall_task.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.state
     *
     * @param state the value for litemall_task.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.integral
     *
     * @return the value of litemall_task.integral
     *
     * @mbg.generated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.integral
     *
     * @param integral the value for litemall_task.integral
     *
     * @mbg.generated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.time
     *
     * @return the value of litemall_task.time
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.time
     *
     * @param time the value for litemall_task.time
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.number_static
     *
     * @return the value of litemall_task.number_static
     *
     * @mbg.generated
     */
    public Integer getNumberStatic() {
        return numberStatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.number_static
     *
     * @param numberStatic the value for litemall_task.number_static
     *
     * @mbg.generated
     */
    public void setNumberStatic(Integer numberStatic) {
        this.numberStatic = numberStatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.begin_timeFrom
     *
     * @return the value of litemall_task.begin_timeFrom
     *
     * @mbg.generated
     */
    public String getBeginTimefrom() {
        return beginTimefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.begin_timeFrom
     *
     * @param beginTimefrom the value for litemall_task.begin_timeFrom
     *
     * @mbg.generated
     */
    public void setBeginTimefrom(String beginTimefrom) {
        this.beginTimefrom = beginTimefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.begin_timeTo
     *
     * @return the value of litemall_task.begin_timeTo
     *
     * @mbg.generated
     */
    public String getBeginTimeto() {
        return beginTimeto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.begin_timeTo
     *
     * @param beginTimeto the value for litemall_task.begin_timeTo
     *
     * @mbg.generated
     */
    public void setBeginTimeto(String beginTimeto) {
        this.beginTimeto = beginTimeto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_task.real_dieTime
     *
     * @return the value of litemall_task.real_dieTime
     *
     * @mbg.generated
     */
    public String getRealDietime() {
        return realDietime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_task.real_dieTime
     *
     * @param realDietime the value for litemall_task.real_dieTime
     *
     * @mbg.generated
     */
    public void setRealDietime(String realDietime) {
        this.realDietime = realDietime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roomAddress=").append(roomAddress);
        sb.append(", duration=").append(duration);
        sb.append(", videoName=").append(videoName);
        sb.append(", number=").append(number);
        sb.append(", roomId=").append(roomId);
        sb.append(", state=").append(state);
        sb.append(", integral=").append(integral);
        sb.append(", time=").append(time);
        sb.append(", numberStatic=").append(numberStatic);
        sb.append(", beginTimefrom=").append(beginTimefrom);
        sb.append(", beginTimeto=").append(beginTimeto);
        sb.append(", realDietime=").append(realDietime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallTask other = (LitemallTask) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoomAddress() == null ? other.getRoomAddress() == null : this.getRoomAddress().equals(other.getRoomAddress()))
            && (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()))
            && (this.getVideoName() == null ? other.getVideoName() == null : this.getVideoName().equals(other.getVideoName()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getRoomId() == null ? other.getRoomId() == null : this.getRoomId().equals(other.getRoomId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getIntegral() == null ? other.getIntegral() == null : this.getIntegral().equals(other.getIntegral()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getNumberStatic() == null ? other.getNumberStatic() == null : this.getNumberStatic().equals(other.getNumberStatic()))
            && (this.getBeginTimefrom() == null ? other.getBeginTimefrom() == null : this.getBeginTimefrom().equals(other.getBeginTimefrom()))
            && (this.getBeginTimeto() == null ? other.getBeginTimeto() == null : this.getBeginTimeto().equals(other.getBeginTimeto()))
            && (this.getRealDietime() == null ? other.getRealDietime() == null : this.getRealDietime().equals(other.getRealDietime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoomAddress() == null) ? 0 : getRoomAddress().hashCode());
        result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
        result = prime * result + ((getVideoName() == null) ? 0 : getVideoName().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getRoomId() == null) ? 0 : getRoomId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getIntegral() == null) ? 0 : getIntegral().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getNumberStatic() == null) ? 0 : getNumberStatic().hashCode());
        result = prime * result + ((getBeginTimefrom() == null) ? 0 : getBeginTimefrom().hashCode());
        result = prime * result + ((getBeginTimeto() == null) ? 0 : getBeginTimeto().hashCode());
        result = prime * result + ((getRealDietime() == null) ? 0 : getRealDietime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        roomAddress("room_address", "roomAddress", "VARCHAR", false),
        duration("duration", "duration", "DECIMAL", false),
        videoName("video_name", "videoName", "VARCHAR", false),
        number("number", "number", "INTEGER", true),
        roomId("room_id", "roomId", "VARCHAR", false),
        state("state", "state", "VARCHAR", true),
        integral("integral", "integral", "INTEGER", false),
        time("time", "time", "VARCHAR", true),
        numberStatic("number_static", "numberStatic", "INTEGER", false),
        beginTimefrom("begin_timeFrom", "beginTimefrom", "VARCHAR", false),
        beginTimeto("begin_timeTo", "beginTimeto", "VARCHAR", false),
        realDietime("real_dieTime", "realDietime", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_task
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}